spring:
  application:
    name: cloudbalance
  datasource:
#    mysql:
    url: jdbc:mysql://localhost:3306/cloudDB
    username: saumya
    password: sam1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  snowflake:
    datasource:
      url: jdbc:snowflake://IVLLMDL-CG35370.snowflakecomputing.com/?warehouse=COMPUTE_WH&db=CLOUDBALANCE_SNOWFLAKE
      username: SAUMYA17
      password: sAm@1234567890
      driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  app:
    jwtSecret: "mysecretkeyismysecretkeynoneofyoursecretkey"
    jwtExpirationMs: 900000
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect